import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  documentationSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  documentationSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'PART ONE - INTRODUCTION TO AFYA MSAFIRI',
      items: [''PART ONE - INTRODUCTION TO AFYA MSAFIRI/background',
      'PART ONE - INTRODUCTION TO AFYA MSAFIRI/objectives',
      'PART ONE - INTRODUCTION TO AFYA MSAFIRI/rationale',
      'PART ONE - INTRODUCTION TO AFYA MSAFIRI/scope',
      '],
    },
    (
     type: 'category',
      label: 'PART TWO - PART TWO - SYSTEM REQUIREMENTS AND COMPONENTS',
      items: ['PART TWO - SYSTEM REQUIREMENTS AND COMPONENTS/docs/PART TWO - SYSTEM REQUIREMENTS AND COMPONENTS/System access REqurements',
      'PART TWO - SYSTEM REQUIREMENTS AND COMPONENTS/docs/PART TWO - SYSTEM REQUIREMENTS AND COMPONENTS /system components',
    ],
),
(
 type: 'category',
      label: 'AFYA MSAFIRI FOR TRAVELERS',
      items: ['AFYA MSAFIRI FOR TRAVELERS/AFYA MSAFIRI FOR TRAVELERS',
      
],
),
( type: 'category',
      label: 'AFYA MSAFIRI  SYSTEM FOR MANAGERS ',
      items: ['AFYA MSAFIRI  SYSTEM FOR MANAGERS/AFYA MSAFIRI  SYSTEM FOR MANAGERS  ',
],    
),
    */
};

export default sidebars;
